spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      database: izivia-tokens
grpc:
  server:
    port: 8092
  client:
    grpc-client-electrical-service:
      address: static://localhost:8090
      negotiationType: plaintext


