spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      database: izivia-organizations
grpc:
  client:
    grpc-client-service:
      address: static://localhost:8090
      negotiationType: plaintext

  server:
    port: 8090    #default port 9090
